import { utils } from "./../utils.js";

export class Maps {
  constructor() {
    this.maps = {
      Outside: {
        id: "Outside",
        lowerSrc: "./assets/maps/newmaps/start-area-outside-lowerImage.png",
        upperSrc: "./assets/maps/newmaps/start-area-outside-upperImage.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(17),
            y: utils.withGrid(20),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
          npcA: {
            type: "Person",
            x: utils.withGrid(20),
            y: utils.withGrid(19),
            src: "./assets/characters/people/npc1.png",
            behaviorLoop: [
              { type: "stand", direction: "down", time: 3000 },
              { type: "stand", direction: "right", time: 3000 },
            ],
            talking: [
              {
                required: ["TALKED_TO_ERIO"],
                events: [{ type: "textMessage", text: "Isn't Erio the coolest?", faceHero: "npcA" }],
              },
              {
                events: [{ type: "textMessage", text: "Hey!", faceHero: "npcA" }],
              },
            ],
          },
        },
        walls: {
          [utils.asGridCoord(19, 1)]: true,
          [utils.asGridCoord(21, 1)]: true,
          [utils.asGridCoord(36, 1)]: true,
          [utils.asGridCoord(39, 1)]: true,
          [utils.asGridCoord(13, 2)]: true,
          [utils.asGridCoord(14, 2)]: true,
          [utils.asGridCoord(19, 2)]: true,
          [utils.asGridCoord(21, 2)]: true,
          [utils.asGridCoord(26, 2)]: true,
          [utils.asGridCoord(45, 6)]: true,
          [utils.asGridCoord(27, 2)]: true,
          [utils.asGridCoord(28, 2)]: true,
          [utils.asGridCoord(29, 2)]: true,
          [utils.asGridCoord(36, 2)]: true,
          [utils.asGridCoord(39, 2)]: true,
          [utils.asGridCoord(12, 3)]: true,
          [utils.asGridCoord(15, 3)]: true,
          [utils.asGridCoord(19, 3)]: true,
          [utils.asGridCoord(22, 3)]: true,
          [utils.asGridCoord(23, 3)]: true,
          [utils.asGridCoord(24, 3)]: true,
          [utils.asGridCoord(25, 3)]: true,
          [utils.asGridCoord(30, 3)]: true,
          [utils.asGridCoord(36, 3)]: true,
          [utils.asGridCoord(39, 3)]: true,
          [utils.asGridCoord(12, 4)]: true,
          [utils.asGridCoord(15, 4)]: true,
          [utils.asGridCoord(18, 4)]: true,
          [utils.asGridCoord(30, 4)]: true,
          [utils.asGridCoord(36, 4)]: true,
          [utils.asGridCoord(39, 4)]: true,
          [utils.asGridCoord(13, 5)]: true,
          [utils.asGridCoord(15, 5)]: true,
          [utils.asGridCoord(18, 5)]: true,
          [utils.asGridCoord(30, 5)]: true,
          [utils.asGridCoord(31, 5)]: true,
          [utils.asGridCoord(32, 5)]: true,
          [utils.asGridCoord(33, 5)]: true,
          [utils.asGridCoord(34, 5)]: true,
          [utils.asGridCoord(35, 5)]: true,
          [utils.asGridCoord(36, 5)]: true,
          [utils.asGridCoord(39, 5)]: true,
          [utils.asGridCoord(40, 5)]: true,
          [utils.asGridCoord(13, 6)]: true,
          [utils.asGridCoord(15, 6)]: true,
          [utils.asGridCoord(18, 6)]: true,
          [utils.asGridCoord(41, 6)]: true,
          [utils.asGridCoord(13, 7)]: true,
          [utils.asGridCoord(15, 7)]: true,
          [utils.asGridCoord(17, 7)]: true,
          [utils.asGridCoord(41, 7)]: true,
          [utils.asGridCoord(43, 7)]: true,
          [utils.asGridCoord(44, 7)]: true,
          [utils.asGridCoord(46, 7)]: true,
          [utils.asGridCoord(13, 8)]: true,
          [utils.asGridCoord(15, 8)]: true,
          [utils.asGridCoord(16, 8)]: true,
          [utils.asGridCoord(17, 8)]: true,
          [utils.asGridCoord(18, 8)]: true,
          [utils.asGridCoord(19, 8)]: true,
          [utils.asGridCoord(22, 8)]: true,
          [utils.asGridCoord(23, 8)]: true,
          [utils.asGridCoord(24, 8)]: true,
          [utils.asGridCoord(25, 8)]: true,
          [utils.asGridCoord(26, 8)]: true,
          [utils.asGridCoord(27, 8)]: true,
          [utils.asGridCoord(28, 8)]: true,
          [utils.asGridCoord(29, 8)]: true,
          [utils.asGridCoord(30, 8)]: true,
          [utils.asGridCoord(31, 8)]: true,
          [utils.asGridCoord(32, 8)]: true,
          [utils.asGridCoord(33, 8)]: true,
          [utils.asGridCoord(34, 8)]: true,
          [utils.asGridCoord(35, 8)]: true,
          [utils.asGridCoord(36, 8)]: true,
          [utils.asGridCoord(37, 8)]: true,
          [utils.asGridCoord(38, 8)]: true,
          [utils.asGridCoord(39, 8)]: true,
          [utils.asGridCoord(40, 8)]: true,
          [utils.asGridCoord(41, 8)]: true,
          [utils.asGridCoord(42, 8)]: true,
          [utils.asGridCoord(13, 9)]: true,
          [utils.asGridCoord(13, 10)]: true,
          [utils.asGridCoord(12, 11)]: true,
          [utils.asGridCoord(15, 11)]: true,
          [utils.asGridCoord(16, 11)]: true,
          [utils.asGridCoord(17, 11)]: true,
          [utils.asGridCoord(18, 11)]: true,
          [utils.asGridCoord(19, 11)]: true,
          [utils.asGridCoord(20, 11)]: true,
          [utils.asGridCoord(36, 11)]: true,
          [utils.asGridCoord(37, 11)]: true,
          [utils.asGridCoord(38, 11)]: true,
          [utils.asGridCoord(12, 12)]: true,
          [utils.asGridCoord(15, 12)]: true,
          [utils.asGridCoord(17, 12)]: true,
          [utils.asGridCoord(27, 12)]: true,
          [utils.asGridCoord(28, 12)]: true,
          [utils.asGridCoord(29, 12)]: true,
          [utils.asGridCoord(36, 12)]: true,
          [utils.asGridCoord(37, 12)]: true,
          [utils.asGridCoord(38, 12)]: true,
          [utils.asGridCoord(12, 13)]: true,
          [utils.asGridCoord(15, 13)]: true,
          [utils.asGridCoord(17, 13)]: true,
          [utils.asGridCoord(27, 13)]: true,
          [utils.asGridCoord(29, 13)]: true,
          [utils.asGridCoord(31, 13)]: true,
          [utils.asGridCoord(32, 13)]: true,
          [utils.asGridCoord(33, 13)]: true,
          [utils.asGridCoord(34, 13)]: true,
          [utils.asGridCoord(35, 13)]: true,
          [utils.asGridCoord(36, 13)]: true,
          [utils.asGridCoord(38, 13)]: true,
          [utils.asGridCoord(12, 14)]: true,
          [utils.asGridCoord(15, 14)]: true,
          [utils.asGridCoord(16, 14)]: true,
          [utils.asGridCoord(17, 14)]: true,
          [utils.asGridCoord(27, 14)]: true,
          [utils.asGridCoord(29, 14)]: true,
          [utils.asGridCoord(31, 14)]: true,
          [utils.asGridCoord(35, 14)]: true,
          [utils.asGridCoord(44, 14)]: true,
          [utils.asGridCoord(45, 14)]: true,
          [utils.asGridCoord(46, 15)]: true,
          [utils.asGridCoord(12, 15)]: true,
          [utils.asGridCoord(20, 15)]: true,
          [utils.asGridCoord(21, 15)]: true,
          [utils.asGridCoord(22, 15)]: true,
          [utils.asGridCoord(23, 15)]: true,
          [utils.asGridCoord(27, 15)]: true,
          [utils.asGridCoord(29, 15)]: true,
          [utils.asGridCoord(31, 15)]: true,
          [utils.asGridCoord(32, 15)]: true,
          [utils.asGridCoord(34, 15)]: true,
          [utils.asGridCoord(35, 15)]: true,
          [utils.asGridCoord(44, 15)]: true,
          [utils.asGridCoord(12, 16)]: true,
          [utils.asGridCoord(20, 16)]: true,
          [utils.asGridCoord(23, 16)]: true,
          [utils.asGridCoord(44, 16)]: true,
          [utils.asGridCoord(12, 17)]: true,
          [utils.asGridCoord(13, 17)]: true,
          [utils.asGridCoord(14, 17)]: true,
          [utils.asGridCoord(15, 17)]: true,
          [utils.asGridCoord(16, 17)]: true,
          [utils.asGridCoord(17, 17)]: true,
          [utils.asGridCoord(18, 17)]: true,
          [utils.asGridCoord(19, 17)]: true,
          [utils.asGridCoord(20, 17)]: true,
          [utils.asGridCoord(23, 17)]: true,
          [utils.asGridCoord(39, 17)]: true,
          [utils.asGridCoord(43, 17)]: true,
          [utils.asGridCoord(16, 18)]: true,
          [utils.asGridCoord(18, 18)]: true,
          [utils.asGridCoord(19, 18)]: true,
          [utils.asGridCoord(27, 18)]: true,
          [utils.asGridCoord(28, 18)]: true,
          [utils.asGridCoord(29, 18)]: true,
          [utils.asGridCoord(39, 18)]: true,
          [utils.asGridCoord(43, 18)]: true,
          [utils.asGridCoord(15, 19)]: true,
          [utils.asGridCoord(16, 19)]: true,
          [utils.asGridCoord(18, 19)]: true,
          [utils.asGridCoord(19, 19)]: true,
          [utils.asGridCoord(26, 19)]: true,
          [utils.asGridCoord(30, 19)]: true,
          [utils.asGridCoord(31, 19)]: true,
          [utils.asGridCoord(32, 19)]: true,
          [utils.asGridCoord(33, 19)]: true,
          [utils.asGridCoord(34, 19)]: true,
          [utils.asGridCoord(35, 19)]: true,
          [utils.asGridCoord(36, 19)]: true,
          [utils.asGridCoord(37, 19)]: true,
          [utils.asGridCoord(38, 19)]: true,
          [utils.asGridCoord(40, 19)]: true,
          [utils.asGridCoord(41, 19)]: true,
          [utils.asGridCoord(42, 19)]: true,
          [utils.asGridCoord(14, 20)]: true,
          [utils.asGridCoord(27, 20)]: true,
          [utils.asGridCoord(14, 21)]: true,
          [utils.asGridCoord(27, 21)]: true,
          [utils.asGridCoord(14, 22)]: true,
          [utils.asGridCoord(15, 22)]: true,
          [utils.asGridCoord(16, 22)]: true,
          [utils.asGridCoord(17, 22)]: true,
          [utils.asGridCoord(18, 22)]: true,
          [utils.asGridCoord(26, 22)]: true,
          [utils.asGridCoord(18, 23)]: true,
          [utils.asGridCoord(21, 23)]: true,
          [utils.asGridCoord(22, 23)]: true,
          [utils.asGridCoord(23, 23)]: true,
          [utils.asGridCoord(24, 23)]: true,
          [utils.asGridCoord(25, 23)]: true,
          [utils.asGridCoord(26, 23)]: true,
          [utils.asGridCoord(18, 24)]: true,
          [utils.asGridCoord(21, 24)]: true,
          [utils.asGridCoord(17, 25)]: true,
          [utils.asGridCoord(18, 25)]: true,
          [utils.asGridCoord(21, 25)]: true,
          [utils.asGridCoord(22, 25)]: true,
          [utils.asGridCoord(16, 26)]: true,
          [utils.asGridCoord(23, 26)]: true,
          [utils.asGridCoord(16, 27)]: true,
          [utils.asGridCoord(17, 27)]: true,
          [utils.asGridCoord(18, 27)]: true,
          [utils.asGridCoord(23, 27)]: true,
        },
        cutsceneSpaces: {
          /* Outside - NPC interactions */
          [utils.asGridCoord(7, 4)]: [
            {
              events: [
                { who: "npcB", type: "walk", direction: "left" },
                { who: "npcB", type: "stand", direction: "up", time: 500 },
                { type: "textMessage", text: "You can't be in there!" },
                { who: "npcB", type: "walk", direction: "right" },
                { who: "hero", type: "walk", direction: "down" },
                { who: "hero", type: "walk", direction: "left" },
              ],
            },
          ],
          /* Outside - NPC interactions end */

          /* Outside - Room map changes */
          [utils.asGridCoord(20, 2)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LocalShop",
                  x: utils.withGrid(4),
                  y: utils.withGrid(10),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(33, 14)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Mansion",
                  x: utils.withGrid(10),
                  y: utils.withGrid(16),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(17, 18)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Home",
                  x: utils.withGrid(4),
                  y: utils.withGrid(6),
                  direction: "up",
                },
              ],
            },
          ],
          /* Outside - Room map changes end */

          /* Outside - Map changing */
          [utils.asGridCoord(20, 27)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(8),
                  y: utils.withGrid(1),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(19, 27)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(7),
                  y: utils.withGrid(1),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(21, 27)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(8),
                  y: utils.withGrid(1),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(22, 27)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(8),
                  y: utils.withGrid(1),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 8)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(9),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(9),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 10)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(10),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 11)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(10),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 12)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(10),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(46, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(10),
                  direction: "right",
                },
              ],
            },
          ],
          /* Outside - Map changing end */
        },
      },
      Home: {
        id: "Home",
        lowerSrc: "./assets/maps/newmaps/start-area-home.png",
        upperSrc: "",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(17),
            y: utils.withGrid(20),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(1, 1)]: true,
          [utils.asGridCoord(2, 1)]: true,
          [utils.asGridCoord(3, 1)]: true,
          [utils.asGridCoord(4, 1)]: true,
          [utils.asGridCoord(5, 1)]: true,
          [utils.asGridCoord(6, 1)]: true,
          [utils.asGridCoord(7, 1)]: true,
          [utils.asGridCoord(0, 2)]: true,
          [utils.asGridCoord(8, 2)]: true,
          [utils.asGridCoord(8, 3)]: true,
          [utils.asGridCoord(0, 3)]: true,
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(0, 4)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(0, 5)]: true,
          [utils.asGridCoord(8, 6)]: true,
          [utils.asGridCoord(0, 6)]: true,
          [utils.asGridCoord(8, 7)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(2, 7)]: true,
          [utils.asGridCoord(3, 7)]: true,
          [utils.asGridCoord(5, 7)]: true,
          [utils.asGridCoord(6, 7)]: true,
          [utils.asGridCoord(7, 7)]: true,
          [utils.asGridCoord(7, 4)]: true,
        },
        cutsceneSpaces: {
          /* Home - NPC interactions */
          /* Home - NPC interactions end */

          /* Home - Map changing */
          [utils.asGridCoord(4, 7)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(17),
                  y: utils.withGrid(19),
                  direction: "down",
                },
              ],
            },
          ],
          /* Home - Map changing end */
        },
      },
      LowerLeft: {
        id: "LowerLeft",
        lowerSrc: "./assets/maps/newmaps/bottom-left-area_lower.png",
        upperSrc: "./assets/maps/newmaps/bottom-left-area_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(7),
            y: utils.withGrid(1),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(3, 0)]: true,
          [utils.asGridCoord(4, 0)]: true,
          [utils.asGridCoord(5, 0)]: true,
          [utils.asGridCoord(6, 0)]: true,
          [utils.asGridCoord(9, 0)]: true,
          [utils.asGridCoord(1, 1)]: true,
          [utils.asGridCoord(2, 1)]: true,
          [utils.asGridCoord(9, 1)]: true,
          [utils.asGridCoord(10, 1)]: true,
          [utils.asGridCoord(11, 1)]: true,
          [utils.asGridCoord(12, 1)]: true,
          [utils.asGridCoord(13, 1)]: true,
          [utils.asGridCoord(15, 1)]: true,
          [utils.asGridCoord(16, 1)]: true,
          [utils.asGridCoord(17, 1)]: true,
          [utils.asGridCoord(18, 1)]: true,
          [utils.asGridCoord(19, 1)]: true,
          [utils.asGridCoord(20, 1)]: true,
          [utils.asGridCoord(21, 1)]: true,
          [utils.asGridCoord(22, 1)]: true,
          [utils.asGridCoord(23, 1)]: true,
          [utils.asGridCoord(0, 2)]: true,
          [utils.asGridCoord(14, 2)]: true,
          [utils.asGridCoord(24, 2)]: true,
          [utils.asGridCoord(25, 2)]: true,
          [utils.asGridCoord(26, 2)]: true,
          [utils.asGridCoord(27, 2)]: true,
          [utils.asGridCoord(0, 3)]: true,
          [utils.asGridCoord(4, 3)]: true,
          [utils.asGridCoord(0, 4)]: true,
          [utils.asGridCoord(0, 5)]: true,
          [utils.asGridCoord(3, 5)]: true,
          [utils.asGridCoord(26, 5)]: true,
          [utils.asGridCoord(27, 5)]: true,
          [utils.asGridCoord(28, 6)]: true,
          [utils.asGridCoord(0, 6)]: true,
          [utils.asGridCoord(3, 6)]: true,
          [utils.asGridCoord(6, 6)]: true,
          [utils.asGridCoord(7, 6)]: true,
          [utils.asGridCoord(24, 6)]: true,
          [utils.asGridCoord(25, 6)]: true,
          [utils.asGridCoord(0, 7)]: true,
          [utils.asGridCoord(3, 7)]: true,
          [utils.asGridCoord(6, 7)]: true,
          [utils.asGridCoord(24, 7)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(3, 8)]: true,
          [utils.asGridCoord(6, 8)]: true,
          [utils.asGridCoord(10, 8)]: true,
          [utils.asGridCoord(24, 8)]: true,
          [utils.asGridCoord(1, 9)]: true,
          [utils.asGridCoord(2, 9)]: true,
          [utils.asGridCoord(3, 9)]: true,
          [utils.asGridCoord(6, 9)]: true,
          [utils.asGridCoord(7, 9)]: true,
          [utils.asGridCoord(8, 9)]: true,
          [utils.asGridCoord(12, 9)]: true,
          [utils.asGridCoord(13, 9)]: true,
          [utils.asGridCoord(14, 9)]: true,
          [utils.asGridCoord(15, 9)]: true,
          [utils.asGridCoord(16, 9)]: true,
          [utils.asGridCoord(17, 9)]: true,
          [utils.asGridCoord(18, 9)]: true,
          [utils.asGridCoord(19, 9)]: true,
          [utils.asGridCoord(20, 9)]: true,
          [utils.asGridCoord(21, 9)]: true,
          [utils.asGridCoord(22, 9)]: true,
          [utils.asGridCoord(23, 9)]: true,
          [utils.asGridCoord(3, 10)]: true,
          [utils.asGridCoord(6, 10)]: true,
          [utils.asGridCoord(3, 11)]: true,
          [utils.asGridCoord(6, 11)]: true,
          [utils.asGridCoord(3, 12)]: true,
          [utils.asGridCoord(6, 12)]: true,
          [utils.asGridCoord(3, 13)]: true,
          [utils.asGridCoord(6, 13)]: true,
          [utils.asGridCoord(3, 14)]: true,
          [utils.asGridCoord(6, 14)]: true,
          [utils.asGridCoord(3, 15)]: true,
          [utils.asGridCoord(6, 15)]: true,
          [utils.asGridCoord(3, 16)]: true,
          [utils.asGridCoord(6, 16)]: true,
          [utils.asGridCoord(2, 17)]: true,
          [utils.asGridCoord(3, 17)]: true,
          [utils.asGridCoord(6, 17)]: true,
          [utils.asGridCoord(7, 17)]: true,
          [utils.asGridCoord(1, 18)]: true,
          [utils.asGridCoord(3, 18)]: true,
          [utils.asGridCoord(8, 18)]: true,
          [utils.asGridCoord(1, 19)]: true,
          [utils.asGridCoord(3, 19)]: true,
          [utils.asGridCoord(6, 19)]: true,
          [utils.asGridCoord(7, 19)]: true,
          [utils.asGridCoord(8, 19)]: true,
          [utils.asGridCoord(1, 20)]: true,
          [utils.asGridCoord(3, 20)]: true,
          [utils.asGridCoord(9, 20)]: true,
          [utils.asGridCoord(0, 21)]: true,
          [utils.asGridCoord(6, 21)]: true,
          [utils.asGridCoord(7, 21)]: true,
          [utils.asGridCoord(8, 21)]: true,
          [utils.asGridCoord(1, 22)]: true,
          [utils.asGridCoord(4, 22)]: true,
          [utils.asGridCoord(6, 22)]: true,
          [utils.asGridCoord(2, 23)]: true,
          [utils.asGridCoord(3, 23)]: true,
          [utils.asGridCoord(5, 23)]: true,
        },
        cutsceneSpaces: {
          /* LowerLeft - NPC interactions */
          /* LowerLeft - NPC interactions end */

          /* LowerLeft - Room map changing */
          [utils.asGridCoord(2, 19)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OldManHouse",
                  x: utils.withGrid(4),
                  y: utils.withGrid(8),
                  direction: "up",
                },
              ],
            },
          ],
          /* LowerLeft - Room map changing end */

          /* LowerLeft - Map changing */
          [utils.asGridCoord(7, 0)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(19),
                  y: utils.withGrid(26),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(8, 0)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(20),
                  y: utils.withGrid(26),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(28, 3)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(36),
                  direction: "right",
                },
              ],
            },
          ],
          [utils.asGridCoord(28, 4)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(1),
                  y: utils.withGrid(37),
                  direction: "right",
                },
              ],
            },
          ],
          /* LowerLeft - Map changing end */
        },
      },
      OutsideRight: {
        id: "OutsideRight",
        lowerSrc: "./assets/maps/newmaps/right-area_lower.png",
        upperSrc: "./assets/maps/newmaps/right-area_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(1),
            y: utils.withGrid(9),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(8, 1)]: true,
          [utils.asGridCoord(26, 25)]: true,
          [utils.asGridCoord(26, 32)]: true,
          [utils.asGridCoord(7, 2)]: true,
          [utils.asGridCoord(9, 2)]: true,
          [utils.asGridCoord(5, 3)]: true,
          [utils.asGridCoord(6, 3)]: true,
          [utils.asGridCoord(7, 3)]: true,
          [utils.asGridCoord(9, 3)]: true,
          [utils.asGridCoord(13, 3)]: true,
          [utils.asGridCoord(17, 3)]: true,
          [utils.asGridCoord(18, 3)]: true,
          [utils.asGridCoord(19, 3)]: true,
          [utils.asGridCoord(20, 3)]: true,
          [utils.asGridCoord(21, 3)]: true,
          [utils.asGridCoord(22, 3)]: true,
          [utils.asGridCoord(23, 3)]: true,
          [utils.asGridCoord(24, 3)]: true,
          [utils.asGridCoord(25, 3)]: true,
          [utils.asGridCoord(2, 4)]: true,
          [utils.asGridCoord(3, 4)]: true,
          [utils.asGridCoord(4, 4)]: true,
          [utils.asGridCoord(10, 4)]: true,
          [utils.asGridCoord(12, 4)]: true,
          [utils.asGridCoord(14, 4)]: true,
          [utils.asGridCoord(16, 4)]: true,
          [utils.asGridCoord(26, 5)]: true,
          [utils.asGridCoord(1, 5)]: true,
          [utils.asGridCoord(10, 5)]: true,
          [utils.asGridCoord(12, 5)]: true,
          [utils.asGridCoord(14, 5)]: true,
          [utils.asGridCoord(16, 5)]: true,
          [utils.asGridCoord(26, 6)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(10, 6)]: true,
          [utils.asGridCoord(11, 6)]: true,
          [utils.asGridCoord(12, 6)]: true,
          [utils.asGridCoord(14, 6)]: true,
          [utils.asGridCoord(15, 6)]: true,
          [utils.asGridCoord(16, 6)]: true,
          [utils.asGridCoord(24, 6)]: true,
          [utils.asGridCoord(25, 6)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(23, 7)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(1, 8)]: true,
          [utils.asGridCoord(23, 8)]: true,
          [utils.asGridCoord(23, 9)]: true,
          [utils.asGridCoord(23, 10)]: true,
          [utils.asGridCoord(0, 11)]: true,
          [utils.asGridCoord(1, 11)]: true,
          [utils.asGridCoord(2, 11)]: true,
          [utils.asGridCoord(3, 11)]: true,
          [utils.asGridCoord(4, 11)]: true,
          [utils.asGridCoord(23, 11)]: true,
          [utils.asGridCoord(4, 12)]: true,
          [utils.asGridCoord(23, 12)]: true,
          [utils.asGridCoord(4, 13)]: true,
          [utils.asGridCoord(20, 13)]: true,
          [utils.asGridCoord(21, 13)]: true,
          [utils.asGridCoord(22, 13)]: true,
          [utils.asGridCoord(4, 14)]: true,
          [utils.asGridCoord(10, 14)]: true,
          [utils.asGridCoord(11, 14)]: true,
          [utils.asGridCoord(20, 14)]: true,
          [utils.asGridCoord(4, 15)]: true,
          [utils.asGridCoord(5, 15)]: true,
          [utils.asGridCoord(6, 15)]: true,
          [utils.asGridCoord(7, 15)]: true,
          [utils.asGridCoord(8, 15)]: true,
          [utils.asGridCoord(9, 15)]: true,
          [utils.asGridCoord(11, 15)]: true,
          [utils.asGridCoord(17, 15)]: true,
          [utils.asGridCoord(18, 15)]: true,
          [utils.asGridCoord(19, 15)]: true,
          [utils.asGridCoord(20, 15)]: true,
          [utils.asGridCoord(4, 16)]: true,
          [utils.asGridCoord(5, 16)]: true,
          [utils.asGridCoord(7, 16)]: true,
          [utils.asGridCoord(8, 16)]: true,
          [utils.asGridCoord(9, 16)]: true,
          [utils.asGridCoord(10, 16)]: true,
          [utils.asGridCoord(11, 16)]: true,
          [utils.asGridCoord(17, 16)]: true,
          [utils.asGridCoord(19, 16)]: true,
          [utils.asGridCoord(20, 16)]: true,
          [utils.asGridCoord(21, 16)]: true,
          [utils.asGridCoord(4, 17)]: true,
          [utils.asGridCoord(21, 17)]: true,
          [utils.asGridCoord(22, 17)]: true,
          [utils.asGridCoord(4, 18)]: true,
          [utils.asGridCoord(23, 18)]: true,
          [utils.asGridCoord(3, 19)]: true,
          [utils.asGridCoord(15, 19)]: true,
          [utils.asGridCoord(16, 19)]: true,
          [utils.asGridCoord(17, 19)]: true,
          [utils.asGridCoord(18, 19)]: true,
          [utils.asGridCoord(19, 19)]: true,
          [utils.asGridCoord(20, 19)]: true,
          [utils.asGridCoord(23, 19)]: true,
          [utils.asGridCoord(2, 20)]: true,
          [utils.asGridCoord(15, 20)]: true,
          [utils.asGridCoord(17, 20)]: true,
          [utils.asGridCoord(20, 20)]: true,
          [utils.asGridCoord(23, 20)]: true,
          [utils.asGridCoord(1, 21)]: true,
          [utils.asGridCoord(5, 21)]: true,
          [utils.asGridCoord(6, 21)]: true,
          [utils.asGridCoord(7, 21)]: true,
          [utils.asGridCoord(8, 21)]: true,
          [utils.asGridCoord(9, 21)]: true,
          [utils.asGridCoord(15, 21)]: true,
          [utils.asGridCoord(16, 21)]: true,
          [utils.asGridCoord(18, 21)]: true,
          [utils.asGridCoord(20, 21)]: true,
          [utils.asGridCoord(23, 21)]: true,
          [utils.asGridCoord(24, 21)]: true,
          [utils.asGridCoord(1, 22)]: true,
          [utils.asGridCoord(5, 22)]: true,
          [utils.asGridCoord(6, 22)]: true,
          [utils.asGridCoord(8, 22)]: true,
          [utils.asGridCoord(9, 22)]: true,
          [utils.asGridCoord(15, 22)]: true,
          [utils.asGridCoord(16, 22)]: true,
          [utils.asGridCoord(18, 22)]: true,
          [utils.asGridCoord(20, 22)]: true,
          [utils.asGridCoord(25, 22)]: true,
          [utils.asGridCoord(1, 23)]: true,
          [utils.asGridCoord(15, 23)]: true,
          [utils.asGridCoord(16, 23)]: true,
          [utils.asGridCoord(18, 23)]: true,
          [utils.asGridCoord(20, 23)]: true,
          [utils.asGridCoord(25, 23)]: true,
          [utils.asGridCoord(2, 24)]: true,
          [utils.asGridCoord(4, 24)]: true,
          [utils.asGridCoord(15, 24)]: true,
          [utils.asGridCoord(16, 24)]: true,
          [utils.asGridCoord(19, 24)]: true,
          [utils.asGridCoord(20, 24)]: true,
          [utils.asGridCoord(21, 24)]: true,
          [utils.asGridCoord(24, 24)]: true,
          [utils.asGridCoord(25, 24)]: true,
          [utils.asGridCoord(3, 25)]: true,
          [utils.asGridCoord(5, 25)]: true,
          [utils.asGridCoord(6, 25)]: true,
          [utils.asGridCoord(7, 25)]: true,
          [utils.asGridCoord(8, 25)]: true,
          [utils.asGridCoord(9, 25)]: true,
          [utils.asGridCoord(10, 25)]: true,
          [utils.asGridCoord(11, 25)]: true,
          [utils.asGridCoord(26, 26)]: true,
          [utils.asGridCoord(2, 26)]: true,
          [utils.asGridCoord(26, 27)]: true,
          [utils.asGridCoord(1, 27)]: true,
          [utils.asGridCoord(26, 28)]: true,
          [utils.asGridCoord(2, 28)]: true,
          [utils.asGridCoord(26, 29)]: true,
          [utils.asGridCoord(3, 29)]: true,
          [utils.asGridCoord(4, 29)]: true,
          [utils.asGridCoord(5, 29)]: true,
          [utils.asGridCoord(6, 29)]: true,
          [utils.asGridCoord(7, 29)]: true,
          [utils.asGridCoord(8, 29)]: true,
          [utils.asGridCoord(9, 29)]: true,
          [utils.asGridCoord(10, 29)]: true,
          [utils.asGridCoord(26, 30)]: true,
          [utils.asGridCoord(4, 30)]: true,
          [utils.asGridCoord(6, 30)]: true,
          [utils.asGridCoord(8, 30)]: true,
          [utils.asGridCoord(10, 30)]: true,
          [utils.asGridCoord(24, 30)]: true,
          [utils.asGridCoord(25, 30)]: true,
          [utils.asGridCoord(3, 31)]: true,
          [utils.asGridCoord(4, 31)]: true,
          [utils.asGridCoord(7, 31)]: true,
          [utils.asGridCoord(10, 31)]: true,
          [utils.asGridCoord(25, 31)]: true,
          [utils.asGridCoord(2, 32)]: true,
          [utils.asGridCoord(10, 32)]: true,
          [utils.asGridCoord(26, 33)]: true,
          [utils.asGridCoord(2, 33)]: true,
          [utils.asGridCoord(3, 33)]: true,
          [utils.asGridCoord(4, 33)]: true,
          [utils.asGridCoord(7, 33)]: true,
          [utils.asGridCoord(8, 33)]: true,
          [utils.asGridCoord(9, 33)]: true,
          [utils.asGridCoord(10, 33)]: true,
          [utils.asGridCoord(18, 33)]: true,
          [utils.asGridCoord(26, 34)]: true,
          [utils.asGridCoord(1, 34)]: true,
          [utils.asGridCoord(18, 34)]: true,
          [utils.asGridCoord(26, 35)]: true,
          [utils.asGridCoord(0, 35)]: true,
          [utils.asGridCoord(1, 35)]: true,
          [utils.asGridCoord(18, 35)]: true,
          [utils.asGridCoord(26, 36)]: true,
          [utils.asGridCoord(18, 36)]: true,
          [utils.asGridCoord(26, 37)]: true,
          [utils.asGridCoord(18, 37)]: true,
          [utils.asGridCoord(26, 38)]: true,
          [utils.asGridCoord(0, 38)]: true,
          [utils.asGridCoord(18, 38)]: true,
          [utils.asGridCoord(26, 39)]: true,
          [utils.asGridCoord(1, 39)]: true,
          [utils.asGridCoord(2, 39)]: true,
          [utils.asGridCoord(18, 39)]: true,
          [utils.asGridCoord(26, 40)]: true,
          [utils.asGridCoord(2, 40)]: true,
          [utils.asGridCoord(18, 40)]: true,
          [utils.asGridCoord(26, 41)]: true,
          [utils.asGridCoord(3, 41)]: true,
          [utils.asGridCoord(4, 41)]: true,
          [utils.asGridCoord(5, 41)]: true,
          [utils.asGridCoord(6, 41)]: true,
          [utils.asGridCoord(7, 41)]: true,
          [utils.asGridCoord(8, 41)]: true,
          [utils.asGridCoord(9, 41)]: true,
          [utils.asGridCoord(10, 41)]: true,
          [utils.asGridCoord(11, 41)]: true,
          [utils.asGridCoord(12, 41)]: true,
          [utils.asGridCoord(13, 41)]: true,
          [utils.asGridCoord(14, 41)]: true,
          [utils.asGridCoord(15, 41)]: true,
          [utils.asGridCoord(16, 41)]: true,
          [utils.asGridCoord(17, 41)]: true,
          [utils.asGridCoord(19, 41)]: true,
          [utils.asGridCoord(20, 41)]: true,
          [utils.asGridCoord(21, 41)]: true,
          [utils.asGridCoord(22, 41)]: true,
          [utils.asGridCoord(23, 41)]: true,
          [utils.asGridCoord(24, 41)]: true,
          [utils.asGridCoord(25, 41)]: true,
        },
        cutsceneSpaces: {
          /* OutsideRight - NPC interactions */
          /* OutsideRight - NPC interactions end */

          /* OutsideRight - Room map changing */
          [utils.asGridCoord(13, 5)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Arena",
                  x: utils.withGrid(9),
                  y: utils.withGrid(12),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(5, 30)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "BigHouse",
                  x: utils.withGrid(9),
                  y: utils.withGrid(12),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(18, 16)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "SmallHouse",
                  x: utils.withGrid(4),
                  y: utils.withGrid(8),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(17, 22)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "MediumHouse",
                  x: utils.withGrid(3),
                  y: utils.withGrid(9),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(6, 16)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "SocialClubRoom",
                  x: utils.withGrid(4),
                  y: utils.withGrid(11),
                  direction: "up",
                },
              ],
            },
          ],
          [utils.asGridCoord(7, 22)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "SmallShop",
                  x: utils.withGrid(5),
                  y: utils.withGrid(7),
                  direction: "up",
                },
              ],
            },
          ],
          /* OutsideRight - Room map changing end  */

          /* OutsideRight - Map changing  */
          [utils.asGridCoord(0, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(45),
                  y: utils.withGrid(9),
                  direction: "left",
                },
              ],
            },
          ],
          [utils.asGridCoord(0, 10)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(45),
                  y: utils.withGrid(10),
                  direction: "left",
                },
              ],
            },
          ],
          [utils.asGridCoord(0, 37)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(27),
                  y: utils.withGrid(4),
                  direction: "left",
                },
              ],
            },
          ],
          [utils.asGridCoord(0, 36)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(27),
                  y: utils.withGrid(3),
                  direction: "left",
                },
              ],
            },
          ],
          /* OutsideRight - Map changing end  */
        },
      },

      Mansion: {
        id: "Mansion",
        lowerSrc: "./assets/maps/newmaps/room1_lower.png",
        upperSrc: "./assets/maps/newmaps/room1_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(10),
            y: utils.withGrid(16),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(9, 4)]: true,
          [utils.asGridCoord(10, 4)]: true,
          [utils.asGridCoord(11, 4)]: true,
          [utils.asGridCoord(12, 4)]: true,
          [utils.asGridCoord(13, 4)]: true,
          [utils.asGridCoord(14, 4)]: true,
          [utils.asGridCoord(15, 4)]: true,
          [utils.asGridCoord(16, 4)]: true,
          [utils.asGridCoord(17, 4)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(18, 5)]: true,
          [utils.asGridCoord(7, 6)]: true,
          [utils.asGridCoord(18, 6)]: true,
          [utils.asGridCoord(7, 7)]: true,
          [utils.asGridCoord(18, 7)]: true,
          [utils.asGridCoord(7, 8)]: true,
          [utils.asGridCoord(18, 8)]: true,
          [utils.asGridCoord(3, 9)]: true,
          [utils.asGridCoord(4, 9)]: true,
          [utils.asGridCoord(5, 9)]: true,
          [utils.asGridCoord(6, 9)]: true,
          [utils.asGridCoord(7, 9)]: true,
          [utils.asGridCoord(8, 9)]: true,
          [utils.asGridCoord(9, 9)]: true,
          [utils.asGridCoord(10, 9)]: true,
          [utils.asGridCoord(11, 9)]: true,
          [utils.asGridCoord(14, 9)]: true,
          [utils.asGridCoord(15, 9)]: true,
          [utils.asGridCoord(16, 9)]: true,
          [utils.asGridCoord(17, 9)]: true,
          [utils.asGridCoord(2, 10)]: true,
          [utils.asGridCoord(16, 10)]: true,
          [utils.asGridCoord(17, 10)]: true,
          [utils.asGridCoord(1, 11)]: true,
          [utils.asGridCoord(18, 11)]: true,
          [utils.asGridCoord(1, 12)]: true,
          [utils.asGridCoord(4, 12)]: true,
          [utils.asGridCoord(5, 12)]: true,
          [utils.asGridCoord(6, 12)]: true,
          [utils.asGridCoord(18, 12)]: true,
          [utils.asGridCoord(1, 13)]: true,
          [utils.asGridCoord(4, 13)]: true,
          [utils.asGridCoord(5, 13)]: true,
          [utils.asGridCoord(6, 13)]: true,
          [utils.asGridCoord(18, 13)]: true,
          [utils.asGridCoord(1, 14)]: true,
          [utils.asGridCoord(4, 14)]: true,
          [utils.asGridCoord(5, 14)]: true,
          [utils.asGridCoord(6, 14)]: true,
          [utils.asGridCoord(18, 14)]: true,
          [utils.asGridCoord(2, 15)]: true,
          [utils.asGridCoord(18, 15)]: true,
          [utils.asGridCoord(2, 16)]: true,
          [utils.asGridCoord(17, 16)]: true,
          [utils.asGridCoord(3, 17)]: true,
          [utils.asGridCoord(4, 17)]: true,
          [utils.asGridCoord(5, 17)]: true,
          [utils.asGridCoord(6, 17)]: true,
          [utils.asGridCoord(7, 17)]: true,
          [utils.asGridCoord(8, 17)]: true,
          [utils.asGridCoord(9, 17)]: true,
          [utils.asGridCoord(12, 17)]: true,
          [utils.asGridCoord(13, 17)]: true,
          [utils.asGridCoord(14, 17)]: true,
          [utils.asGridCoord(15, 17)]: true,
          [utils.asGridCoord(16, 17)]: true,
        },
        cutsceneSpaces: {
          /* Mansion - NPC interactions */
          /* Mansion - NPC interactions end */

          /* Mansion - Room map changing */
          [utils.asGridCoord(10, 17)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(33),
                  y: utils.withGrid(15),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(11, 17)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(33),
                  y: utils.withGrid(15),
                  direction: "down",
                },
              ],
            },
          ],
          /* Mansion - Room map changing end  */
        },
      },
      OldManHouse: {
        id: "OldManHouse",
        lowerSrc: "./assets/maps/newmaps/room2_lower.png",
        upperSrc: "./assets/maps/newmaps/room2_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(4),
            y: utils.withGrid(8),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(1, 2)]: true,
          [utils.asGridCoord(0, 3)]: true,
          [utils.asGridCoord(2, 3)]: true,
          [utils.asGridCoord(5, 3)]: true,
          [utils.asGridCoord(0, 4)]: true,
          [utils.asGridCoord(2, 4)]: true,
          [utils.asGridCoord(3, 4)]: true,
          [utils.asGridCoord(4, 4)]: true,
          [utils.asGridCoord(6, 4)]: true,
          [utils.asGridCoord(0, 5)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(0, 6)]: true,
          [utils.asGridCoord(8, 6)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(9, 7)]: true,
          [utils.asGridCoord(9, 8)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(9, 9)]: true,
          [utils.asGridCoord(1, 9)]: true,
          [utils.asGridCoord(2, 9)]: true,
          [utils.asGridCoord(3, 9)]: true,
          [utils.asGridCoord(6, 9)]: true,
          [utils.asGridCoord(7, 9)]: true,
          [utils.asGridCoord(8, 9)]: true,
        },
        cutsceneSpaces: {
          /* OldManHouse - NPC interactions */
          /* OldManHouse - NPC interactions end */

          /* OldManHouse - Room map changing */
          [utils.asGridCoord(4, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(2),
                  y: utils.withGrid(20),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(5, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "LowerLeft",
                  x: utils.withGrid(2),
                  y: utils.withGrid(20),
                  direction: "down",
                },
              ],
            },
          ],
          /* OldManHouse - Room map changing end */
        },
      },
      SocialClubRoom: {
        id: "SocialClubRoom",
        lowerSrc: "./assets/maps/newmaps/room3_lower.png",
        upperSrc: "./assets/maps/newmaps/room3_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(4),
            y: utils.withGrid(10),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(2, 1)]: true,
          [utils.asGridCoord(3, 1)]: true,
          [utils.asGridCoord(4, 1)]: true,
          [utils.asGridCoord(5, 1)]: true,
          [utils.asGridCoord(6, 1)]: true,
          [utils.asGridCoord(7, 1)]: true,
          [utils.asGridCoord(8, 1)]: true,
          [utils.asGridCoord(9, 1)]: true,
          [utils.asGridCoord(10, 1)]: true,
          [utils.asGridCoord(11, 1)]: true,
          [utils.asGridCoord(12, 1)]: true,
          [utils.asGridCoord(1, 2)]: true,
          [utils.asGridCoord(13, 3)]: true,
          [utils.asGridCoord(1, 3)]: true,
          [utils.asGridCoord(13, 4)]: true,
          [utils.asGridCoord(1, 4)]: true,
          [utils.asGridCoord(4, 4)]: true,
          [utils.asGridCoord(5, 4)]: true,
          [utils.asGridCoord(6, 4)]: true,
          [utils.asGridCoord(7, 4)]: true,
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(9, 4)]: true,
          [utils.asGridCoord(10, 4)]: true,
          [utils.asGridCoord(13, 5)]: true,
          [utils.asGridCoord(1, 5)]: true,
          [utils.asGridCoord(4, 5)]: true,
          [utils.asGridCoord(5, 5)]: true,
          [utils.asGridCoord(6, 5)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(9, 5)]: true,
          [utils.asGridCoord(10, 5)]: true,
          [utils.asGridCoord(13, 6)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(13, 7)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(13, 8)]: true,
          [utils.asGridCoord(1, 8)]: true,
          [utils.asGridCoord(13, 9)]: true,
          [utils.asGridCoord(1, 9)]: true,
          [utils.asGridCoord(13, 10)]: true,
          [utils.asGridCoord(1, 10)]: true,
          [utils.asGridCoord(11, 10)]: true,
          [utils.asGridCoord(12, 10)]: true,
          [utils.asGridCoord(1, 11)]: true,
          [utils.asGridCoord(12, 11)]: true,
          [utils.asGridCoord(2, 12)]: true,
          [utils.asGridCoord(3, 12)]: true,
          [utils.asGridCoord(6, 12)]: true,
          [utils.asGridCoord(7, 12)]: true,
          [utils.asGridCoord(8, 12)]: true,
          [utils.asGridCoord(9, 12)]: true,
          [utils.asGridCoord(10, 12)]: true,
          [utils.asGridCoord(11, 12)]: true,
        },
        cutsceneSpaces: {
          /* SocialClubRoom - NPC interactions */
          /* SocialClubRoom - NPC interactions end */

          /* SocialClubRoom - Room map changing */
          [utils.asGridCoord(4, 12)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(6),
                  y: utils.withGrid(17),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(5, 12)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(6),
                  y: utils.withGrid(17),
                  direction: "down",
                },
              ],
            },
          ],
          /* SocialClubRoom - Room map changing end */
        },
      },
      SmallHouse: {
        id: "SmallHouse",
        lowerSrc: "./assets/maps/newmaps/room4_lower.png",
        upperSrc: "./assets/maps/newmaps/room4_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(5),
            y: utils.withGrid(8),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(3, 1)]: true,
          [utils.asGridCoord(9, 2)]: true,
          [utils.asGridCoord(4, 1)]: true,
          [utils.asGridCoord(5, 1)]: true,
          [utils.asGridCoord(7, 1)]: true,
          [utils.asGridCoord(8, 1)]: true,
          [utils.asGridCoord(1, 2)]: true,
          [utils.asGridCoord(2, 2)]: true,
          [utils.asGridCoord(6, 2)]: true,
          [utils.asGridCoord(9, 3)]: true,
          [utils.asGridCoord(1, 3)]: true,
          [utils.asGridCoord(9, 4)]: true,
          [utils.asGridCoord(1, 4)]: true,
          [utils.asGridCoord(7, 4)]: true,
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(1, 5)]: true,
          [utils.asGridCoord(2, 5)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(2, 6)]: true,
          [utils.asGridCoord(9, 7)]: true,
          [utils.asGridCoord(0, 7)]: true,
          [utils.asGridCoord(9, 8)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(9, 9)]: true,
          [utils.asGridCoord(1, 9)]: true,
          [utils.asGridCoord(2, 9)]: true,
          [utils.asGridCoord(3, 9)]: true,
          [utils.asGridCoord(6, 9)]: true,
          [utils.asGridCoord(7, 9)]: true,
          [utils.asGridCoord(8, 9)]: true,
        },
        cutsceneSpaces: {
          /* SmallHouse - NPC interactions */
          /* SmallHouse - NPC interactions end */
          /* SmallHouse - Room map changing */
          [utils.asGridCoord(5, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(18),
                  y: utils.withGrid(17),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(4, 9)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(18),
                  y: utils.withGrid(17),
                  direction: "down",
                },
              ],
            },
          ],
          /* SmallHouse - Room map changing end */
        },
      },
      MediumHouse: {
        id: "MediumHouse",
        lowerSrc: "./assets/maps/newmaps/room5_lower.png",
        upperSrc: "./assets/maps/newmaps/room5_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(4),
            y: utils.withGrid(9),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(7, 1)]: true,
          [utils.asGridCoord(8, 1)]: true,
          [utils.asGridCoord(9, 1)]: true,
          [utils.asGridCoord(10, 1)]: true,
          [utils.asGridCoord(11, 1)]: true,
          [utils.asGridCoord(12, 2)]: true,
          [utils.asGridCoord(5, 1)]: true,
          [utils.asGridCoord(6, 1)]: true,
          [utils.asGridCoord(12, 3)]: true,
          [utils.asGridCoord(4, 3)]: true,
          [utils.asGridCoord(12, 4)]: true,
          [utils.asGridCoord(5, 4)]: true,
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(12, 5)]: true,
          [utils.asGridCoord(2, 5)]: true,
          [utils.asGridCoord(3, 5)]: true,
          [utils.asGridCoord(4, 5)]: true,
          [utils.asGridCoord(5, 5)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(12, 6)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(12, 7)]: true,
          [utils.asGridCoord(0, 7)]: true,
          [utils.asGridCoord(12, 8)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(11, 8)]: true,
          [utils.asGridCoord(0, 9)]: true,
          [utils.asGridCoord(11, 9)]: true,
          [utils.asGridCoord(1, 10)]: true,
          [utils.asGridCoord(2, 10)]: true,
          [utils.asGridCoord(5, 10)]: true,
          [utils.asGridCoord(6, 10)]: true,
          [utils.asGridCoord(7, 10)]: true,
          [utils.asGridCoord(8, 10)]: true,
          [utils.asGridCoord(9, 10)]: true,
          [utils.asGridCoord(10, 10)]: true,
        },
        cutsceneSpaces: {
          /* MediumHouse - NPC interactions */
          /* MediumHouse - NPC interactions end */
          /* MediumHouse - Room map changing */
          [utils.asGridCoord(3, 10)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(17),
                  y: utils.withGrid(23),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(4, 10)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(17),
                  y: utils.withGrid(23),
                  direction: "down",
                },
              ],
            },
          ],
          /* MediumHouse - Room map changing end */
        },
      },
      BigHouse: {
        id: "BigHouse",
        lowerSrc: "./assets/maps/newmaps/room6_lower.png",
        upperSrc: "./assets/maps/newmaps/room6_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(9),
            y: utils.withGrid(12),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(1, 2)]: true,
          [utils.asGridCoord(2, 2)]: true,
          [utils.asGridCoord(3, 2)]: true,
          [utils.asGridCoord(4, 2)]: true,
          [utils.asGridCoord(5, 2)]: true,
          [utils.asGridCoord(6, 2)]: true,
          [utils.asGridCoord(13, 2)]: true,
          [utils.asGridCoord(14, 2)]: true,
          [utils.asGridCoord(15, 2)]: true,
          [utils.asGridCoord(16, 2)]: true,
          [utils.asGridCoord(0, 3)]: true,
          [utils.asGridCoord(2, 3)]: true,
          [utils.asGridCoord(7, 3)]: true,
          [utils.asGridCoord(12, 3)]: true,
          [utils.asGridCoord(17, 3)]: true,
          [utils.asGridCoord(0, 4)]: true,
          [utils.asGridCoord(7, 4)]: true,
          [utils.asGridCoord(12, 4)]: true,
          [utils.asGridCoord(18, 4)]: true,
          [utils.asGridCoord(1, 5)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(9, 5)]: true,
          [utils.asGridCoord(10, 5)]: true,
          [utils.asGridCoord(11, 5)]: true,
          [utils.asGridCoord(12, 5)]: true,
          [utils.asGridCoord(18, 5)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(7, 6)]: true,
          [utils.asGridCoord(18, 6)]: true,
          [utils.asGridCoord(0, 7)]: true,
          [utils.asGridCoord(7, 7)]: true,
          [utils.asGridCoord(18, 7)]: true,
          [utils.asGridCoord(1, 8)]: true,
          [utils.asGridCoord(2, 8)]: true,
          [utils.asGridCoord(5, 8)]: true,
          [utils.asGridCoord(6, 8)]: true,
          [utils.asGridCoord(7, 8)]: true,
          [utils.asGridCoord(8, 8)]: true,
          [utils.asGridCoord(11, 8)]: true,
          [utils.asGridCoord(12, 8)]: true,
          [utils.asGridCoord(13, 8)]: true,
          [utils.asGridCoord(14, 8)]: true,
          [utils.asGridCoord(15, 8)]: true,
          [utils.asGridCoord(16, 8)]: true,
          [utils.asGridCoord(17, 8)]: true,
          [utils.asGridCoord(0, 9)]: true,
          [utils.asGridCoord(18, 9)]: true,
          [utils.asGridCoord(0, 10)]: true,
          [utils.asGridCoord(18, 10)]: true,
          [utils.asGridCoord(0, 11)]: true,
          [utils.asGridCoord(18, 11)]: true,
          [utils.asGridCoord(0, 12)]: true,
          [utils.asGridCoord(18, 12)]: true,
          [utils.asGridCoord(1, 13)]: true,
          [utils.asGridCoord(2, 13)]: true,
          [utils.asGridCoord(3, 13)]: true,
          [utils.asGridCoord(4, 13)]: true,
          [utils.asGridCoord(5, 13)]: true,
          [utils.asGridCoord(6, 13)]: true,
          [utils.asGridCoord(7, 13)]: true,
          [utils.asGridCoord(8, 13)]: true,
          [utils.asGridCoord(11, 13)]: true,
          [utils.asGridCoord(12, 13)]: true,
          [utils.asGridCoord(13, 13)]: true,
          [utils.asGridCoord(14, 13)]: true,
          [utils.asGridCoord(15, 13)]: true,
          [utils.asGridCoord(16, 13)]: true,
          [utils.asGridCoord(17, 13)]: true,
        },
        cutsceneSpaces: {
          /* BigHouse - NPC interactions */
          /* BigHouse - NPC interactions end */
          /* BigHouse - Room map changing */
          [utils.asGridCoord(9, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(5),
                  y: utils.withGrid(31),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(10, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(5),
                  y: utils.withGrid(31),
                  direction: "down",
                },
              ],
            },
          ],
          /* BigHouse - Room map changing end */
        },
      },
      Arena: {
        id: "Arena",
        lowerSrc: "./assets/maps/newmaps/room7_lower.png",
        upperSrc: "./assets/maps/newmaps/room7_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(9),
            y: utils.withGrid(12),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(19, 3)]: true,
          [utils.asGridCoord(1, 2)]: true,
          [utils.asGridCoord(2, 2)]: true,
          [utils.asGridCoord(3, 2)]: true,
          [utils.asGridCoord(4, 2)]: true,
          [utils.asGridCoord(5, 2)]: true,
          [utils.asGridCoord(6, 2)]: true,
          [utils.asGridCoord(7, 2)]: true,
          [utils.asGridCoord(8, 2)]: true,
          [utils.asGridCoord(9, 2)]: true,
          [utils.asGridCoord(10, 2)]: true,
          [utils.asGridCoord(11, 2)]: true,
          [utils.asGridCoord(12, 2)]: true,
          [utils.asGridCoord(13, 2)]: true,
          [utils.asGridCoord(14, 2)]: true,
          [utils.asGridCoord(15, 2)]: true,
          [utils.asGridCoord(16, 2)]: true,
          [utils.asGridCoord(17, 2)]: true,
          [utils.asGridCoord(18, 2)]: true,
          [utils.asGridCoord(0, 3)]: true,
          [utils.asGridCoord(19, 4)]: true,
          [utils.asGridCoord(0, 4)]: true,
          [utils.asGridCoord(19, 5)]: true,
          [utils.asGridCoord(0, 5)]: true,
          [utils.asGridCoord(19, 6)]: true,
          [utils.asGridCoord(0, 6)]: true,
          [utils.asGridCoord(19, 7)]: true,
          [utils.asGridCoord(0, 7)]: true,
          [utils.asGridCoord(19, 8)]: true,
          [utils.asGridCoord(0, 8)]: true,
          [utils.asGridCoord(19, 9)]: true,
          [utils.asGridCoord(0, 9)]: true,
          [utils.asGridCoord(19, 10)]: true,
          [utils.asGridCoord(0, 10)]: true,
          [utils.asGridCoord(19, 11)]: true,
          [utils.asGridCoord(0, 11)]: true,
          [utils.asGridCoord(19, 12)]: true,
          [utils.asGridCoord(0, 12)]: true,
          [utils.asGridCoord(19, 13)]: true,
          [utils.asGridCoord(1, 13)]: true,
          [utils.asGridCoord(2, 13)]: true,
          [utils.asGridCoord(3, 13)]: true,
          [utils.asGridCoord(4, 13)]: true,
          [utils.asGridCoord(5, 13)]: true,
          [utils.asGridCoord(6, 13)]: true,
          [utils.asGridCoord(7, 13)]: true,
          [utils.asGridCoord(12, 13)]: true,
          [utils.asGridCoord(13, 13)]: true,
          [utils.asGridCoord(14, 13)]: true,
          [utils.asGridCoord(15, 13)]: true,
          [utils.asGridCoord(16, 13)]: true,
          [utils.asGridCoord(17, 13)]: true,
          [utils.asGridCoord(18, 13)]: true,
        },
        cutsceneSpaces: {
          /* Arena - NPC interactions */
          /* Arena - NPC interactions end */
          /* Arena - Room map changing */
          [utils.asGridCoord(8, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(13),
                  y: utils.withGrid(6),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(9, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(13),
                  y: utils.withGrid(6),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(10, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(13),
                  y: utils.withGrid(6),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(11, 13)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(13),
                  y: utils.withGrid(6),
                  direction: "down",
                },
              ],
            },
          ],
          /* Arena - Room map changing end */
        },
      },

      SmallShop: {
        id: "SmallShop",
        lowerSrc: "./assets/maps/newmaps/shop1_lower.png",
        upperSrc: "./assets/maps/newmaps/shop1_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(5),
            y: utils.withGrid(7),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(2, 4)]: true,
          [utils.asGridCoord(3, 4)]: true,
          [utils.asGridCoord(4, 4)]: true,
          [utils.asGridCoord(5, 4)]: true,
          [utils.asGridCoord(6, 4)]: true,
          [utils.asGridCoord(7, 4)]: true,
          [utils.asGridCoord(8, 4)]: true,
          [utils.asGridCoord(1, 5)]: true,
          [utils.asGridCoord(9, 5)]: true,
          [utils.asGridCoord(9, 6)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(9, 7)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(9, 8)]: true,
          [utils.asGridCoord(2, 8)]: true,
          [utils.asGridCoord(3, 8)]: true,
          [utils.asGridCoord(4, 8)]: true,
          [utils.asGridCoord(6, 8)]: true,
          [utils.asGridCoord(7, 8)]: true,
          [utils.asGridCoord(8, 8)]: true,
        },
        cutsceneSpaces: {
          /* SmallShop - NPC interactions */
          /* SmallShop - NPC interactions end */
          /* SmallShop - Room map changing */
          [utils.asGridCoord(5, 8)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "OutsideRight",
                  x: utils.withGrid(7),
                  y: utils.withGrid(23),
                  direction: "down",
                },
              ],
            },
          ],
          /* SmallShop - Room map changing end */
        },
      },
      LocalShop: {
        id: "LocalShop",
        lowerSrc: "./assets/maps/newmaps/shop2_lower.png",
        upperSrc: "./assets/maps/newmaps/shop2_upper.png",
        configObjects: {
          hero: {
            type: "Person",
            isPlayerControlled: true,
            src: "./assets/characters/people/hero.png",
            x: utils.withGrid(3),
            y: utils.withGrid(9),
            useShadow: true,
            spriteWidth: 32,
            spriteHeight: 32,
          },
        },
        walls: {
          [utils.asGridCoord(2, 5)]: true,
          [utils.asGridCoord(3, 5)]: true,
          [utils.asGridCoord(4, 5)]: true,
          [utils.asGridCoord(5, 5)]: true,
          [utils.asGridCoord(6, 5)]: true,
          [utils.asGridCoord(7, 5)]: true,
          [utils.asGridCoord(8, 5)]: true,
          [utils.asGridCoord(9, 5)]: true,
          [utils.asGridCoord(10, 5)]: true,
          [utils.asGridCoord(11, 5)]: true,
          [utils.asGridCoord(12, 5)]: true,
          [utils.asGridCoord(13, 5)]: true,
          [utils.asGridCoord(14, 6)]: true,
          [utils.asGridCoord(14, 7)]: true,
          [utils.asGridCoord(13, 8)]: true,
          [utils.asGridCoord(13, 10)]: true,
          [utils.asGridCoord(1, 6)]: true,
          [utils.asGridCoord(1, 7)]: true,
          [utils.asGridCoord(1, 8)]: true,
          [utils.asGridCoord(1, 9)]: true,
          [utils.asGridCoord(1, 10)]: true,
          [utils.asGridCoord(13, 9)]: true,
          [utils.asGridCoord(2, 11)]: true,
          [utils.asGridCoord(3, 11)]: true,
          [utils.asGridCoord(6, 11)]: true,
          [utils.asGridCoord(7, 11)]: true,
          [utils.asGridCoord(8, 11)]: true,
          [utils.asGridCoord(9, 11)]: true,
          [utils.asGridCoord(10, 11)]: true,
          [utils.asGridCoord(11, 11)]: true,
          [utils.asGridCoord(12, 11)]: true,
        },
        cutsceneSpaces: {
          [utils.asGridCoord(4, 11)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(20),
                  y: utils.withGrid(3),
                  direction: "down",
                },
              ],
            },
          ],
          [utils.asGridCoord(5, 11)]: [
            {
              events: [
                {
                  type: "changeMap",
                  map: "Outside",
                  x: utils.withGrid(20),
                  y: utils.withGrid(3),
                  direction: "down",
                },
              ],
            },
          ],
        },
      },
    };
  }
}
