import { utils } from "../../utils.js";

/**  */
const changeMapToOutsideRightUpperTile = [
  {
    events: [
      {
        type: "changeMap",
        map: "OutsideRight",
        x: utils.withGrid(1),
        y: utils.withGrid(9),
        direction: "right",
      },
    ],
  },
];

const changeMapToOutsideRightLowerTile = [
  {
    events: [
      {
        type: "changeMap",
        map: "OutsideRight",
        x: utils.withGrid(1),
        y: utils.withGrid(10),
        direction: "right",
      },
    ],
  },
];

const changeMapToOutsideBottomLeftTile = [
  {
    events: [
      {
        type: "changeMap",
        map: "OutsideBottom",
        x: utils.withGrid(7),
        y: utils.withGrid(1),
        direction: "down",
      },
    ],
  },
];
const changeMapToOutsideBottomRightTile = [
  {
    events: [
      {
        type: "changeMap",
        map: "OutsideBottom",
        x: utils.withGrid(8),
        y: utils.withGrid(1),
        direction: "down",
      },
    ],
  },
];

export const OutsideLeft = {
  id: "OutsideLeft",
  hugMapCorners: true,
  lowerSrc: "./assets/maps/newmaps/start-area-outside-lowerImage.png",
  upperSrc: "./assets/maps/newmaps/start-area-outside-upperImage.png",
  configObjects: {
    hero: {
      type: "Person",
      isPlayerControlled: true,
      src: "./assets/characters/people/hero.png",
      x: utils.withGrid(16),
      y: utils.withGrid(19),
    },
    chest1: {
      type: "Chest",
      x: utils.withGrid(20),
      y: utils.withGrid(15),
      storyFlag: "CHEST1_OUTSIDELEFT",
      item: "item_hayBale",
    },
    chest2: {
      type: "Chest",
      x: utils.withGrid(12),
      y: utils.withGrid(2),
      storyFlag: "CHEST2_OUTSIDELEFT",
      direction: "right",
      item: "item_flySpray",
    },
    fire1: {
      type: "Fire",
      x: utils.withGrid(18) - 1,
      y: utils.withGrid(12) - 7,
    },
    cow1: {
      type: "Cow",
      x: utils.withGrid(20),
      y: utils.withGrid(13),
      behaviorLoop: [
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "stand", direction: "right", time: 4000 },
        { type: "stand", direction: "left", time: 3000 },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "left", time: 3000 },
        { type: "stand", direction: "right", time: 4000 },
      ],
      talking: [
        {
          events: [
            {
              type: "textMessage",
              text: "Moooo!",
            },
            { type: "healAnimals" },
            {
              type: "textMessage",
              text: "Wow talking with the animals has re-invigorated your own.",
            },
          ],
        },
      ],
    },
    chicken1: {
      type: "Chicken",
      x: utils.withGrid(39),
      y: utils.withGrid(13),
      color: "black",
      behaviorLoop: [
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "stand", direction: "right", time: 4000 },
        { type: "stand", direction: "left", time: 3000 },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "left", time: 3000 },
        { type: "stand", direction: "right", time: 4000 },
      ],
      talking: [
        {
          events: [
            {
              type: "textMessage",
              text: "Cluck cluck!",
            },
            { type: "healAnimals" },
            {
              type: "textMessage",
              text: "Wow talking with the animals has re-invigorated your own.",
            },
          ],
        },
      ],
    },
    npc1: {
      type: "Person",
      x: utils.withGrid(19),
      y: utils.withGrid(18),
      src: "./assets/characters/people/alchemist.png",
      behaviorLoop: [
        { type: "stand", direction: "down", time: 3000 },
        { type: "stand", direction: "right", time: 3000 },
      ],
      talking: [
        {
          required: ["TALKED_TO_npc1_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Sandra: If you need any help, just let us know. We're all behind you.",
              faceHero: "npc1",
            },
            {
              type: "textMessage",
              text: "Sandra: Be careful, that secret society is strong. You will want to train your farm animals up.",
            },
          ],
        },
        {
          events: [
            { type: "addStoryFlag", flag: "TALKED_TO_npc1_OUTSIDELEFT" },
            {
              type: "textMessage",
              text: "Sandra: Hey Sam, I heard about your father.",
              faceHero: "npc1",
            },
            {
              type: "textMessage",
              text: "Sandra: Some folks say those people who took your father are part of a secret society.",
            },
            {
              type: "textMessage",
              text: "Sandra: They say they have some kind of grand plan. Ask around, someone must know his whereabouts",
            },
          ],
        },
      ],
    },
    npc2: {
      type: "Person",
      x: utils.withGrid(19),
      y: utils.withGrid(8),
      src: "./assets/characters/people/kid.png",
      behaviorLoop: [
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "right" },
        { type: "walk", direction: "down" },
        { type: "stand", direction: "down", time: 200 },
        { type: "stand", direction: "right", time: 300 },
        { type: "stand", direction: "down", time: 700 },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "down", time: 500 },
        { type: "stand", direction: "right", time: 200 },
        { type: "stand", direction: "down", time: 700 },
        { type: "walk", direction: "down" },
        { type: "walk", direction: "down" },
        { type: "walk", direction: "down" },
        { type: "walk", direction: "down" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "left", time: 600 },
        { type: "stand", direction: "down", time: 200 },
        { type: "stand", direction: "right", time: 200 },
        { type: "walk", direction: "up" },
        { type: "walk", direction: "up" },
        { type: "walk", direction: "up" },
        { type: "walk", direction: "up" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "down", time: 700 },
        { type: "walk", direction: "up" },
        { type: "stand", direction: "up", time: 900 },
        { type: "stand", direction: "left", time: 200 },
        { type: "stand", direction: "right", time: 400 },
      ],
      talking: [
        {
          required: ["DEFEATED_npc2_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Out the way, I need to train up!",
              faceHero: "npc2",
            },
            {
              type: "textMessage",
              text: "I will be as strong as you one day!",
            },
          ],
        },
        {
          events: [
            {
              type: "textMessage",
              text: "Hey! My favourite farm animals are definitely cows! They're so cute and cuddly.",
              faceHero: "npc2",
            },
            { type: "battle", enemyId: "Bob" },
            {
              type: "textMessage",
              text: "Wow, you are so strong!.",
            },
            { type: "addStoryFlag", flag: "DEFEATED_npc2_OUTSIDELEFT" },
          ],
        },
      ],
    },
    npc3: {
      type: "Person",
      x: utils.withGrid(19),
      y: utils.withGrid(11),
      src: "./assets/characters/people/blacksmith.png",
      behaviorLoop: [{ type: "stand", direction: "left", time: 1000 }],
      talking: [
        {
          required: ["TALKED_TO_npc3_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Go speak with John. He lives in the mansion by the water. He should be able to give you what you need.",
              faceHero: "npc3",
            },
          ],
        },
        {
          events: [
            { type: "addStoryFlag", flag: "TALKED_TO_npc3_OUTSIDELEFT" },
            {
              type: "textMessage",
              text: "I heard what happened to your father. It's a shame that such a talented man was taken like that.",
              faceHero: "npc3",
            },
            {
              type: "textMessage",
              text: "Me: Do you know anyone who's familiar with this group that took my father?",
            },
            {
              type: "textMessage",
              text: "Me: I need to find out more about them.",
            },
            {
              type: "textMessage",
              text: "John will be able to help you, he lives in the mansion by the water.",
            },
            {
              type: "textMessage",
              text: "Goodluck",
            },
          ],
        },
      ],
    },
    npc4: {
      type: "Person",
      x: utils.withGrid(20),
      y: utils.withGrid(2),
      src: "./assets/characters/people/kid2.png",
      behaviorLoop: [{ type: "stand", direction: "down", time: 1000 }],
      talking: [
        {
          required: ["DEFEATED_npc4_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Your father is a talented man. We all want to see him safe and sound",
              faceHero: "npc4",
            },
          ],
        },
        {
          events: [
            {
              type: "textMessage",
              text: "Bring it on!",
              faceHero: "npc4",
            },
            { type: "battle", enemyId: "Billy" },
            {
              type: "textMessage",
              text: "Wow, you are so strong!",
            },
            { type: "addStoryFlag", flag: "DEFEATED_npc4_OUTSIDELEFT" },
          ],
        },
      ],
    },
    npc5: {
      type: "Person",
      x: utils.withGrid(37),
      y: utils.withGrid(3),
      src: "./assets/characters/people/merchant2.png",
      behaviorLoop: [{ type: "stand", direction: "down", time: 1000 }],
      talking: [
        {
          required: ["CUTSCENE_npc5_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Unknown: Come back with the password. Only members may come past this point.",
              faceHero: "npc75",
            },
          ],
        },
        {
          events: [
            { type: "addStoryFlag", flag: "TALKED_TO_npc5_OUTSIDELEFT" },
            {
              type: "textMessage",
              text: "Unknown: Only members may come past this point.",
              faceHero: "npc5",
            },
          ],
        },
      ],
    },
    npc6: {
      type: "Person",
      x: utils.withGrid(40),
      y: utils.withGrid(17),
      src: "./assets/characters/people/kid4.png",
      behaviorLoop: [
        { type: "stand", direction: "right", time: 1000 },
        { type: "stand", direction: "down", time: 2000 },
        { type: "walk", direction: "left" },
        { type: "stand", direction: "down", time: 2000 },
        { type: "stand", direction: "up", time: 1000 },
        { type: "walk", direction: "right" },
      ],
      talking: [
        {
          required: ["DEFEATED_npc6_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Wow you are strong!",
              faceHero: "npc6",
            },
          ],
        },
        {
          events: [
            {
              type: "textMessage",
              text: "My brother is really strong, he has been training me!",
              faceHero: "npc6",
            },
            { type: "battle", enemyId: "Penny" },
            { type: "addStoryFlag", flag: "DEFEATED_npc6_OUTSIDELEFT" },
          ],
        },
      ],
    },
    npc7: {
      type: "Person",
      x: utils.withGrid(41),
      y: utils.withGrid(17),
      src: "./assets/characters/people/kid3.png",
      behaviorLoop: [{ type: "stand", direction: "left", time: 1000 }],
      talking: [
        {
          required: ["DEFEATED_npc7_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "I have a lot to learn.",
              faceHero: "npc7",
            },
          ],
        },
        {
          events: [
            {
              type: "textMessage",
              text: "I'm the greatest! Bring it on.",
              faceHero: "npc7",
            },
            { type: "battle", enemyId: "Elly" },
            { type: "addStoryFlag", flag: "DEFEATED_npc7_OUTSIDELEFT" },
          ],
        },
      ],
    },
  },
  walls: {
    [utils.asGridCoord(18, 0)]: true,
    [utils.asGridCoord(20, 0)]: true,
    [utils.asGridCoord(35, 0)]: true,
    [utils.asGridCoord(38, 0)]: true,
    [utils.asGridCoord(12, 1)]: true,
    [utils.asGridCoord(13, 1)]: true,
    [utils.asGridCoord(18, 1)]: true,
    [utils.asGridCoord(20, 1)]: true,
    [utils.asGridCoord(25, 1)]: true,
    [utils.asGridCoord(26, 1)]: true,
    [utils.asGridCoord(27, 1)]: true,
    [utils.asGridCoord(28, 1)]: true,
    [utils.asGridCoord(35, 1)]: true,
    [utils.asGridCoord(38, 1)]: true,
    [utils.asGridCoord(11, 2)]: true,
    [utils.asGridCoord(14, 2)]: true,
    [utils.asGridCoord(18, 2)]: true,
    [utils.asGridCoord(21, 2)]: true,
    [utils.asGridCoord(22, 2)]: true,
    [utils.asGridCoord(23, 2)]: true,
    [utils.asGridCoord(24, 2)]: true,
    [utils.asGridCoord(29, 2)]: true,
    [utils.asGridCoord(35, 2)]: true,
    [utils.asGridCoord(38, 2)]: true,
    [utils.asGridCoord(11, 3)]: true,
    [utils.asGridCoord(14, 3)]: true,
    [utils.asGridCoord(17, 3)]: true,
    [utils.asGridCoord(29, 3)]: true,
    [utils.asGridCoord(35, 3)]: true,
    [utils.asGridCoord(38, 3)]: true,
    [utils.asGridCoord(12, 4)]: true,
    [utils.asGridCoord(14, 4)]: true,
    [utils.asGridCoord(17, 4)]: true,
    [utils.asGridCoord(29, 4)]: true,
    [utils.asGridCoord(30, 4)]: true,
    [utils.asGridCoord(31, 4)]: true,
    [utils.asGridCoord(32, 4)]: true,
    [utils.asGridCoord(33, 4)]: true,
    [utils.asGridCoord(34, 4)]: true,
    [utils.asGridCoord(35, 4)]: true,
    [utils.asGridCoord(38, 4)]: true,
    [utils.asGridCoord(39, 4)]: true,
    [utils.asGridCoord(12, 5)]: true,
    [utils.asGridCoord(14, 5)]: true,
    [utils.asGridCoord(17, 5)]: true,
    [utils.asGridCoord(40, 5)]: true,
    [utils.asGridCoord(12, 6)]: true,
    [utils.asGridCoord(14, 6)]: true,
    [utils.asGridCoord(16, 6)]: true,
    [utils.asGridCoord(40, 6)]: true,
    [utils.asGridCoord(42, 6)]: true,
    [utils.asGridCoord(43, 6)]: true,
    [utils.asGridCoord(44, 6)]: true,
    [utils.asGridCoord(45, 7)]: true,
    [utils.asGridCoord(12, 7)]: true,
    [utils.asGridCoord(14, 7)]: true,
    [utils.asGridCoord(15, 7)]: true,
    [utils.asGridCoord(16, 7)]: true,
    [utils.asGridCoord(17, 7)]: true,
    [utils.asGridCoord(18, 7)]: true,
    [utils.asGridCoord(21, 7)]: true,
    [utils.asGridCoord(22, 7)]: true,
    [utils.asGridCoord(23, 7)]: true,
    [utils.asGridCoord(24, 7)]: true,
    [utils.asGridCoord(25, 7)]: true,
    [utils.asGridCoord(26, 7)]: true,
    [utils.asGridCoord(27, 7)]: true,
    [utils.asGridCoord(28, 7)]: true,
    [utils.asGridCoord(29, 7)]: true,
    [utils.asGridCoord(30, 7)]: true,
    [utils.asGridCoord(31, 7)]: true,
    [utils.asGridCoord(32, 7)]: true,
    [utils.asGridCoord(33, 7)]: true,
    [utils.asGridCoord(34, 7)]: true,
    [utils.asGridCoord(35, 7)]: true,
    [utils.asGridCoord(36, 7)]: true,
    [utils.asGridCoord(37, 7)]: true,
    [utils.asGridCoord(38, 7)]: true,
    [utils.asGridCoord(39, 7)]: true,
    [utils.asGridCoord(40, 7)]: true,
    [utils.asGridCoord(41, 7)]: true,
    [utils.asGridCoord(12, 8)]: true,
    [utils.asGridCoord(12, 9)]: true,
    [utils.asGridCoord(11, 10)]: true,
    [utils.asGridCoord(14, 10)]: true,
    [utils.asGridCoord(15, 10)]: true,
    [utils.asGridCoord(16, 10)]: true,
    [utils.asGridCoord(17, 10)]: true,
    [utils.asGridCoord(18, 10)]: true,
    [utils.asGridCoord(19, 10)]: true,
    [utils.asGridCoord(35, 10)]: true,
    [utils.asGridCoord(36, 10)]: true,
    [utils.asGridCoord(37, 10)]: true,
    [utils.asGridCoord(11, 11)]: true,
    [utils.asGridCoord(14, 11)]: true,
    [utils.asGridCoord(16, 11)]: true,
    [utils.asGridCoord(26, 11)]: true,
    [utils.asGridCoord(27, 11)]: true,
    [utils.asGridCoord(28, 11)]: true,
    [utils.asGridCoord(35, 11)]: true,
    [utils.asGridCoord(36, 11)]: true,
    [utils.asGridCoord(37, 11)]: true,
    [utils.asGridCoord(11, 12)]: true,
    [utils.asGridCoord(14, 12)]: true,
    [utils.asGridCoord(16, 12)]: true,
    [utils.asGridCoord(26, 12)]: true,
    [utils.asGridCoord(28, 12)]: true,
    [utils.asGridCoord(30, 12)]: true,
    [utils.asGridCoord(31, 12)]: true,
    [utils.asGridCoord(32, 12)]: true,
    [utils.asGridCoord(33, 12)]: true,
    [utils.asGridCoord(34, 12)]: true,
    [utils.asGridCoord(35, 12)]: true,
    [utils.asGridCoord(37, 12)]: true,
    [utils.asGridCoord(11, 13)]: true,
    [utils.asGridCoord(14, 13)]: true,
    [utils.asGridCoord(15, 13)]: true,
    [utils.asGridCoord(16, 13)]: true,
    [utils.asGridCoord(26, 13)]: true,
    [utils.asGridCoord(28, 13)]: true,
    [utils.asGridCoord(30, 13)]: true,
    [utils.asGridCoord(34, 13)]: true,
    [utils.asGridCoord(43, 13)]: true,
    [utils.asGridCoord(44, 13)]: true,
    [utils.asGridCoord(45, 14)]: true,
    [utils.asGridCoord(11, 14)]: true,
    [utils.asGridCoord(19, 14)]: true,
    [utils.asGridCoord(20, 14)]: true,
    [utils.asGridCoord(21, 14)]: true,
    [utils.asGridCoord(22, 14)]: true,
    [utils.asGridCoord(26, 14)]: true,
    [utils.asGridCoord(27, 14)]: true,
    [utils.asGridCoord(28, 14)]: true,
    [utils.asGridCoord(30, 14)]: true,
    [utils.asGridCoord(31, 14)]: true,
    [utils.asGridCoord(33, 14)]: true,
    [utils.asGridCoord(34, 14)]: true,
    [utils.asGridCoord(43, 14)]: true,
    [utils.asGridCoord(11, 15)]: true,
    [utils.asGridCoord(19, 15)]: true,
    [utils.asGridCoord(22, 15)]: true,
    [utils.asGridCoord(43, 15)]: true,
    [utils.asGridCoord(11, 16)]: true,
    [utils.asGridCoord(12, 16)]: true,
    [utils.asGridCoord(13, 16)]: true,
    [utils.asGridCoord(14, 16)]: true,
    [utils.asGridCoord(15, 16)]: true,
    [utils.asGridCoord(16, 16)]: true,
    [utils.asGridCoord(17, 16)]: true,
    [utils.asGridCoord(18, 16)]: true,
    [utils.asGridCoord(19, 16)]: true,
    [utils.asGridCoord(22, 16)]: true,
    [utils.asGridCoord(38, 16)]: true,
    [utils.asGridCoord(42, 16)]: true,
    [utils.asGridCoord(15, 17)]: true,
    [utils.asGridCoord(17, 17)]: true,
    [utils.asGridCoord(18, 17)]: true,
    [utils.asGridCoord(26, 17)]: true,
    [utils.asGridCoord(27, 17)]: true,
    [utils.asGridCoord(28, 17)]: true,
    [utils.asGridCoord(38, 17)]: true,
    [utils.asGridCoord(42, 17)]: true,
    [utils.asGridCoord(14, 18)]: true,
    [utils.asGridCoord(15, 18)]: true,
    [utils.asGridCoord(17, 18)]: true,
    [utils.asGridCoord(18, 18)]: true,
    [utils.asGridCoord(25, 18)]: true,
    [utils.asGridCoord(29, 18)]: true,
    [utils.asGridCoord(30, 18)]: true,
    [utils.asGridCoord(31, 18)]: true,
    [utils.asGridCoord(32, 18)]: true,
    [utils.asGridCoord(33, 18)]: true,
    [utils.asGridCoord(34, 18)]: true,
    [utils.asGridCoord(35, 18)]: true,
    [utils.asGridCoord(36, 18)]: true,
    [utils.asGridCoord(37, 18)]: true,
    [utils.asGridCoord(39, 18)]: true,
    [utils.asGridCoord(40, 18)]: true,
    [utils.asGridCoord(41, 18)]: true,
    [utils.asGridCoord(13, 19)]: true,
    [utils.asGridCoord(26, 19)]: true,
    [utils.asGridCoord(13, 20)]: true,
    [utils.asGridCoord(26, 20)]: true,
    [utils.asGridCoord(13, 21)]: true,
    [utils.asGridCoord(14, 21)]: true,
    [utils.asGridCoord(15, 21)]: true,
    [utils.asGridCoord(16, 21)]: true,
    [utils.asGridCoord(17, 21)]: true,
    [utils.asGridCoord(25, 21)]: true,
    [utils.asGridCoord(17, 22)]: true,
    [utils.asGridCoord(20, 22)]: true,
    [utils.asGridCoord(21, 22)]: true,
    [utils.asGridCoord(22, 22)]: true,
    [utils.asGridCoord(23, 22)]: true,
    [utils.asGridCoord(24, 22)]: true,
    [utils.asGridCoord(25, 22)]: true,
    [utils.asGridCoord(17, 23)]: true,
    [utils.asGridCoord(20, 23)]: true,
    [utils.asGridCoord(16, 24)]: true,
    [utils.asGridCoord(17, 24)]: true,
    [utils.asGridCoord(20, 24)]: true,
    [utils.asGridCoord(21, 24)]: true,
    [utils.asGridCoord(15, 25)]: true,
    [utils.asGridCoord(22, 25)]: true,
    [utils.asGridCoord(15, 26)]: true,
    [utils.asGridCoord(16, 26)]: true,
    [utils.asGridCoord(17, 26)]: true,
    [utils.asGridCoord(22, 26)]: true,
  },
  cutsceneSpaces: {
    /* Outside - NPC interactions */
    [utils.asGridCoord(36, 2)]: [
      {
        events: [
          { who: "npc5", type: "walk", direction: "up" },
          { who: "npc5", type: "walk", direction: "up" },
          { who: "npc5", type: "walk", direction: "left" },
          { who: "npc5", type: "stand", direction: "down", time: 500 },
          { type: "textMessage", text: "Unknown: What is the password?" },
          { type: "textMessage", text: "Me: huh, what password?" },
          { type: "textMessage", text: "Unknown: I'm sorry you cannot enter here, this is a private area." },
          { who: "hero", type: "walk", direction: "down" },
          { who: "hero", type: "walk", direction: "down" },
          { who: "npc5", type: "walk", direction: "down" },
          { who: "npc5", type: "walk", direction: "down" },
          { type: "textMessage", text: "Unknown: Come back with the password and you can enter." },
          { who: "npc5", type: "walk", direction: "right" },
          { who: "npc5", type: "stand", direction: "down", time: 50 },
          { who: "hero", type: "walk", direction: "down" },
          { type: "addStoryFlag", flag: "CUTSCENE_npc5_OUTSIDELEFT" },
        ],
      },
    ],
    /* Outside - NPC interactions end */

    /* Outside - Room map changes */
    [utils.asGridCoord(19, 1)]: [
      {
        events: [
          {
            type: "changeMap",
            map: "LocalShop",
            x: utils.withGrid(4),
            y: utils.withGrid(10),
            direction: "up",
          },
        ],
      },
    ],
    [utils.asGridCoord(32, 13)]: [
      {
        events: [
          {
            type: "changeMap",
            map: "Mansion",
            x: utils.withGrid(10),
            y: utils.withGrid(16),
            direction: "up",
          },
        ],
      },
    ],
    [utils.asGridCoord(16, 17)]: [
      {
        events: [
          {
            type: "changeMap",
            map: "Home",
            x: utils.withGrid(4),
            y: utils.withGrid(6),
            direction: "up",
          },
        ],
      },
    ],
    /* Outside - Room map changes end */

    /* Outside - Map changing */
    [utils.asGridCoord(18, 26)]: changeMapToOutsideBottomLeftTile,
    [utils.asGridCoord(19, 26)]: changeMapToOutsideBottomRightTile,
    [utils.asGridCoord(20, 26)]: changeMapToOutsideBottomRightTile,
    [utils.asGridCoord(21, 26)]: changeMapToOutsideBottomRightTile,
    [utils.asGridCoord(44, 7)]: changeMapToOutsideRightUpperTile,
    [utils.asGridCoord(45, 8)]: changeMapToOutsideRightUpperTile,
    [utils.asGridCoord(45, 9)]: changeMapToOutsideRightLowerTile,
    [utils.asGridCoord(45, 10)]: changeMapToOutsideRightLowerTile,
    [utils.asGridCoord(45, 11)]: changeMapToOutsideRightLowerTile,
    [utils.asGridCoord(45, 12)]: changeMapToOutsideRightLowerTile,
    /* Outside - Map changing end */
  },
};
